### PR TITLE
about_us

### PR DESCRIPTION
**Pull request by ManviAgarwal-3**
about_us page

### CODE REVIEW

**Review by Kushalrock — CHANGES_REQUESTED** [review]
Don't try to use any kind of custom styles instead use Tailwind only.

**Comment by ManviAgarwal-3** [comment]
@mohdshahzil Please disable the linting for using single quotes and double quotes as it is having problems with next lint

**Review by Kushalrock — APPROVED** [review]
Approved

**Comment by mohdshahzil** [comment]
> @mohdshahzil Please disable the linting for using single quotes and double quotes as it is having problems with next lint

will look onto it

**Pull request merged**
